import React, { useState, useRef, useEffect, forwardRef, useImperativeHandle } from 'react'
import { useAIMessage } from '../context/AIMessageContext'

/**
 * TutorPanel Component
 * AI-powered chat interface for quantum computing assistance
 * Features glassmorphism design with animated message bubbles
 */

// Simulated AI responses for when backend is not available
const SIMULATED_RESPONSES = [
  "Great question! A qubit (quantum bit) is the basic unit of quantum information. Unlike classical bits that are either 0 or 1, qubits can exist in a superposition of both states simultaneously, represented as α|0⟩ + β|1⟩ where |α|² + |β|² = 1.",
  "The Bloch sphere is a geometrical representation of the pure state space of a two-level quantum mechanical system (a qubit). The north pole represents |0⟩, the south pole represents |1⟩, and any point on the sphere represents a possible quantum state.",
  "Superposition is a fundamental principle of quantum mechanics that allows a quantum system to be in multiple states at once until it's measured. This is what gives quantum computers their massive parallel processing power!",
  "Quantum entanglement is a phenomenon where two or more particles become correlated in such a way that the quantum state of each particle cannot be described independently, even when separated by large distances.",
  "Quantum gates are the quantum equivalent of classical logic gates. They manipulate qubits through unitary operations. Common gates include the Hadamard (H), Pauli-X, Pauli-Y, Pauli-Z, CNOT, and Toffoli gates.",
  "The no-cloning theorem is a fundamental result in quantum mechanics that states it's impossible to create an identical copy of an arbitrary unknown quantum state. This has important implications for quantum cryptography.",
  "Quantum decoherence is the loss of quantum coherence when a quantum system interacts with its environment. This is one of the biggest challenges in building practical quantum computers.",
  "A quantum circuit is a model for quantum computation where a sequence of quantum gates are applied to qubits. Think of it like a classical circuit, but using quantum operations!"
]

/**
 * TutorPanel - AI Chat Interface
 * Exposes addMessage function via ref for external components
 */
const TutorPanel = forwardRef((props, ref) => {
  const { registerTutorPanel } = useAIMessage()
  
  const [messages, setMessages] = useState([
    {
      id: 1,
      role: 'ai',
      content: "Welcome to Qubiq! I'm your quantum computing tutor. Ask me anything about qubits, quantum gates, superposition, entanglement, or any other quantum computing concept. I'm here to help you learn!",
      timestamp: new Date()
    }
  ])
  const [inputValue, setInputValue] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const messagesEndRef = useRef(null)

  // Expose addMessage function via ref
  useImperativeHandle(ref, () => ({
    addMessage: (content) => {
      const aiMessage = {
        id: Date.now(),
        role: 'ai',
        content: content,
        timestamp: new Date(),
        isAutoGenerated: true
      }
      setMessages(prev => [...prev, aiMessage])
    }
  }))

  // Register this panel with the context
  useEffect(() => {
    registerTutorPanel(ref)
  }, [ref, registerTutorPanel])

  // Auto-scroll to bottom when messages change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages])

  // Get current time formatted
  const getTimeString = (date) => {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
  }

  // Handle sending a message
  const handleSendMessage = async () => {
    if (!inputValue.trim() || isLoading) return

    const userMessage = {
      id: Date.now(),
      role: 'user',
      content: inputValue.trim(),
      timestamp: new Date()
    }

    setMessages(prev => [...prev, userMessage])
    setInputValue('')
    setIsLoading(true)

    try {
      // Try to call the backend API
      const response = await fetch('/api/ask', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ question: userMessage.content })
      })

      if (response.ok) {
        const data = await response.json()
        const aiMessage = {
          id: Date.now() + 1,
          role: 'ai',
          content: data.answer,
          timestamp: new Date()
        }
        setMessages(prev => [...prev, aiMessage])
      } else {
        throw new Error('API request failed')
      }
    } catch (error) {
      // Fallback to simulated response if backend is unavailable
      console.log('Using simulated response:', error.message)
      
      const randomResponse = SIMULATED_RESPONSES[
        Math.floor(Math.random() * SIMULATED_RESPONSES.length)
      ]
      
      const aiMessage = {
        id: Date.now() + 1,
        role: 'ai',
        content: `${randomResponse}\n\n*(Note: This is a simulated response. For AI-powered answers, please ensure the backend server is running.)*`,
        timestamp: new Date()
      }
      
      setMessages(prev => [...prev, aiMessage])
    } finally {
      setIsLoading(false)
    }
  }

  // Handle Enter key press
  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSendMessage()
    }
  }

  return (
    <div className="tutor-panel">
      {/* Header */}
      <div className="tutor-header">
        <div className="tutor-title">Quantum AI Tutor</div>
        <div className="tutor-subtitle">
          Ask me anything about quantum computing
        </div>
      </div>

      {/* Messages Area */}
      <div className="tutor-messages">
        {messages.map((message) => (
          <div
            key={message.id}
            className={`message ${message.role === 'user' ? 'message-user' : 'message-ai'} ${message.isAutoGenerated ? 'message-auto' : ''}`}
          >
            <div className="message-content">
              {message.content}
            </div>
            <div className="message-time">
              {getTimeString(message.timestamp)}
            </div>
          </div>
        ))}
        
        {/* Loading indicator */}
        {isLoading && (
          <div className="message message-ai">
            <div className="message-content">
              <span style={{ 
                display: 'inline-block',
                animation: 'pulse 1s ease-in-out infinite'
              }}>
                ⚡ Thinking...
              </span>
            </div>
          </div>
        )}
        
        <div ref={messagesEndRef} />
      </div>

      {/* Input Area */}
      <div className="tutor-input-area">
        <div className="tutor-input-wrapper">
          <textarea
            className="tutor-input"
            placeholder="Type your question about quantum computing..."
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyPress={handleKeyPress}
            disabled={isLoading}
            rows={1}
          />
          <button
            className="tutor-send-btn"
            onClick={handleSendMessage}
            disabled={isLoading || !inputValue.trim()}
            title="Send message"
          >
            ➤
          </button>
        </div>
      </div>
    </div>
  )
})

TutorPanel.displayName = 'TutorPanel'

export default TutorPanel
